name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    # Only run if the CI workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
    